spring:
  datasource:
    # Настройки подключения к новой БД MySQL (planer_2)
    url: jdbc:mysql://localhost:3306/planer_2?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root  # Если в XAMPP пароля нет, оставь пустые кавычки ""
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      # Важно: update означает, что Hibernate не удалит твои таблицы, а только обновит их, если надо
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  # Настройки OAuth2 для входа через GitHub
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23li7xOtslqticomZi
            client-secret: fee701073fe32a772e492b447fc1f2920bd3fbad
            scope:
              - user:email
              - read:user

# Настройки для твоего JwtService
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000

server:
  port: 8080