spring:
  datasource:
    # Порт 3306 - стандартный для MySQL
    url: jdbc:mysql://localhost:3306/planer?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root  # Если пароля нет (как часто бывает в XAMPP), оставь тут пустое место!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # Меняем диалект с Postgre на MySQL
        dialect: org.hibernate.dialect.MySQLDialect

#  data:
#    redis:
#      host: localhost
#      port: 6379

# Настройки для JwtService (должны соответствовать пути в @Value)
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000

server:
  port: 8080

#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          github:
#            client-id: ${GITHUB_CLIENT_ID}
#            client-secret: ${GITHUB_CLIENT_SECRET}
#            scope:
#              - user:email
#              - read:user